import type { Metadata } from "next"
import { Recursive } from "next/font/google"

import "./globals.css"

import { Toaster } from "@/components/ui/toaster"
import { Footer } from "@/components/molecules/footer"
import { Navbar } from "@/components/molecules/navbar"

const recursive = Recursive({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${recursive.className} bg-slate-50`}>
        <Navbar />
        <main className="grainy-light flex min-h-[calc(100vh-3.5rem-1px)] flex-col">
          <div className="flex h-full flex-1 flex-col">
            {/* <Providers>{children}</Providers> */}
            {children}
          </div>
          <Footer />
        </main>

        <Toaster />
      </body>
    </html>
  )
}
